require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Minutes::MotionsController do

  # This should return the minimal set of attributes required to create a valid
  # Minutes::Motion. As you add validations to Minutes::Motion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "order" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Minutes::MotionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all minutes_motions as @minutes_motions" do
      motion = Minutes::Motion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:minutes_motions).should eq([motion])
    end
  end

  describe "GET show" do
    it "assigns the requested minutes_motion as @minutes_motion" do
      motion = Minutes::Motion.create! valid_attributes
      get :show, {:id => motion.to_param}, valid_session
      assigns(:minutes_motion).should eq(motion)
    end
  end

  describe "GET new" do
    it "assigns a new minutes_motion as @minutes_motion" do
      get :new, {}, valid_session
      assigns(:minutes_motion).should be_a_new(Minutes::Motion)
    end
  end

  describe "GET edit" do
    it "assigns the requested minutes_motion as @minutes_motion" do
      motion = Minutes::Motion.create! valid_attributes
      get :edit, {:id => motion.to_param}, valid_session
      assigns(:minutes_motion).should eq(motion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Minutes::Motion" do
        expect {
          post :create, {:minutes_motion => valid_attributes}, valid_session
        }.to change(Minutes::Motion, :count).by(1)
      end

      it "assigns a newly created minutes_motion as @minutes_motion" do
        post :create, {:minutes_motion => valid_attributes}, valid_session
        assigns(:minutes_motion).should be_a(Minutes::Motion)
        assigns(:minutes_motion).should be_persisted
      end

      it "redirects to the created minutes_motion" do
        post :create, {:minutes_motion => valid_attributes}, valid_session
        response.should redirect_to(Minutes::Motion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved minutes_motion as @minutes_motion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Minutes::Motion.any_instance.stub(:save).and_return(false)
        post :create, {:minutes_motion => { "order" => "invalid value" }}, valid_session
        assigns(:minutes_motion).should be_a_new(Minutes::Motion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Minutes::Motion.any_instance.stub(:save).and_return(false)
        post :create, {:minutes_motion => { "order" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested minutes_motion" do
        motion = Minutes::Motion.create! valid_attributes
        # Assuming there are no other minutes_motions in the database, this
        # specifies that the Minutes::Motion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Minutes::Motion.any_instance.should_receive(:update).with({ "order" => "1" })
        put :update, {:id => motion.to_param, :minutes_motion => { "order" => "1" }}, valid_session
      end

      it "assigns the requested minutes_motion as @minutes_motion" do
        motion = Minutes::Motion.create! valid_attributes
        put :update, {:id => motion.to_param, :minutes_motion => valid_attributes}, valid_session
        assigns(:minutes_motion).should eq(motion)
      end

      it "redirects to the minutes_motion" do
        motion = Minutes::Motion.create! valid_attributes
        put :update, {:id => motion.to_param, :minutes_motion => valid_attributes}, valid_session
        response.should redirect_to(motion)
      end
    end

    describe "with invalid params" do
      it "assigns the minutes_motion as @minutes_motion" do
        motion = Minutes::Motion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Minutes::Motion.any_instance.stub(:save).and_return(false)
        put :update, {:id => motion.to_param, :minutes_motion => { "order" => "invalid value" }}, valid_session
        assigns(:minutes_motion).should eq(motion)
      end

      it "re-renders the 'edit' template" do
        motion = Minutes::Motion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Minutes::Motion.any_instance.stub(:save).and_return(false)
        put :update, {:id => motion.to_param, :minutes_motion => { "order" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested minutes_motion" do
      motion = Minutes::Motion.create! valid_attributes
      expect {
        delete :destroy, {:id => motion.to_param}, valid_session
      }.to change(Minutes::Motion, :count).by(-1)
    end

    it "redirects to the minutes_motions list" do
      motion = Minutes::Motion.create! valid_attributes
      delete :destroy, {:id => motion.to_param}, valid_session
      response.should redirect_to(minutes_motions_url)
    end
  end

end
